--CREATE DATABASE LowCodeAI;

CREATE TABLE IF NOT EXISTS thread (
    id VARCHAR PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS message (
    id VARCHAR PRIMARY KEY,
    input TEXT,
    answer TEXT,
    thread_id VARCHAR REFERENCES Thread(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS feedback (
    id VARCHAR PRIMARY KEY,
    message_id VARCHAR REFERENCES Message(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    value INTEGER DEFAULT 0
);
