# Generated by Django 5.1.2 on 2024-12-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagev2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='answer_in_lang',
        ),
        migrations.RemoveField(
            model_name='message',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='message',
            name='original_input',
        ),
    ]
